# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: errors/errors.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x65rrors/errors.proto\x12\x06\x65rrors\"(\n\x05\x45rror\x12\x1f\n\x04type\x18\x01 \x01(\x0e\x32\x11.errors.ErrorType*\x16\n\tErrorType\x12\t\n\x05\x46\x61tal\x10\x00\x42\'Z%github.com/vpol/daily-proto-go/errorsb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'errors.errors_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z%github.com/vpol/daily-proto-go/errors'
  _ERRORTYPE._serialized_start=73
  _ERRORTYPE._serialized_end=95
  _ERROR._serialized_start=31
  _ERROR._serialized_end=71
# @@protoc_insertion_point(module_scope)
